config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages, only: [:index, :show]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'

  namespace :admin do
    resources :pages, except: [:show]
    resources :sites, except: [:show]
    resources :sections

    # this is an idea for a solution to adding a link_to_add_nested_fields to a js instance 
    # of a nested fields partial created by a link_to_add_nested_fields link
    # i.e. adding link_to_add_nested_fields within link_to_add_nested_fields without an infinite loop
    # post "/nested_fields/:model(/:id)/build/:association(/:partial)", to: "nested_fields#build", as: :build_fields
  end
end

app/views/admin/pages/_form.html.haml
= form_with model: [:admin, @admin_page] do |f|
  - if @admin_page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_page.errors.count, "error")} prohibited this admin_page from being saved:"
      %ul
        - @admin_page.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :parent
    = f.nesting_parent_select
  .field
    = f.fields_for :sections do |s|
      = render "admin/sections/nested_fields", f: s 
    = link_to_add_nested_fields "+ Section", f, :sections
  .actions
    = f.submit 'Save'

app/views/admin/pages/edit.html.haml
%h1 Editing Page

= render 'form'

= link_to 'Show', @admin_page
\|
= link_to 'Back', admin_pages_path

app/views/admin/pages/index.html.haml
%h1 Listing Pages

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @admin_pages.each do |admin_page|
      %tr
        %td= admin_page.title
        %td= admin_page.parent.title if admin_page.nesting.present?
        %td= admin_page.children.first.title if admin_page.children.present?
        %td= link_to 'Show', admin_page
        %td= link_to 'Edit', edit_admin_page_path(admin_page)
        %td= button_to 'Destroy', admin_page_path(admin_page), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }

%br

= link_to 'New Page', new_admin_page_path

app/views/admin/pages/new.html.haml
%h1 New Page
= render 'form'

= link_to 'Back', admin_pages_path