config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages, only: [:index, :show]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'

  namespace :admin do
    resources :pages, except: [:show]
    resources :sites, except: [:show]
    resources :sections

    # this is an idea for a solution to adding a link_to_add_nested_fields to a js instance 
    # of a nested fields partial created by a link_to_add_nested_fields link
    # i.e. adding link_to_add_nested_fields within link_to_add_nested_fields without an infinite loop
    # post "/nested_fields/:model(/:id)/build/:association(/:partial)", to: "nested_fields#build", as: :build_fields
  end
end

app/models/site.rb
# frozen_string_literal: true

class Site < ApplicationRecord
# need to add domain and subdomain validations
end

app/controllers/admin/sites_controller.rb
# frozen_string_literal: true

# admin namespace
module Admin
  # sites
  class SitesController < ApplicationController
    before_action :set_admin_site, only: %i[edit update destroy]

    # GET /admin/sites or /admin/sites.json
    def index
      @admin_sites = Site.all
    end

    # GET /admin/sites/1 or /admin/sites/1.json
    def show; end

    # GET /admin/sites/new
    def new
      @admin_site = Site.new
    end

    # GET /admin/sites/1/edit
    def edit; end

    # POST /admin/sites or /admin/sites.json
    def create
      @admin_site = Site.new(admin_site_params)

      respond_to do |format|
        if @admin_site.save
          format.html { redirect_to admin_sites_url, notice: 'Site was successfully created.' }
          format.json { render :show, status: :created, location: @admin_site }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @admin_site.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/sites/1 or /admin/sites/1.json
    def update
      respond_to do |format|
        if @admin_site.update(admin_site_params)
          format.html { redirect_to admin_sites_url, notice: 'Site was successfully updated.' }
          format.json { render :show, status: :ok, location: @admin_site }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @admin_site.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/sites/1 or /admin/sites/1.json
    def destroy
      @admin_site.destroy

      respond_to do |format|
        format.html { redirect_to admin_sites_url, notice: 'Site was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_site
      @admin_site = Site.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_site_params
      params.require(:site)
            .permit(
              :domain,
              :name,
              :subdomain
            )
    end
  end
end

app/helpers/admin/sites_helper.rb
# frozen_string_literal: true

module Admin
  # module for sites helper
  module SitesHelper
    # these methods will be used to create select inputs for section layouts belonging to the current site
    # def site_sections
    #   get_haml_filenames("app/views/subdomains/#{current_tenant.subdomain}/sections") | application_snippets
    # end

    def site_sections
      get_haml_filenames('app/views/sections')
    end

    def get_haml_filenames(directory)
      Dir.entries(directory)
        .select { |f| f.end_with? 'html.haml' }
        .map { |f| f.chomp('.html.haml') }
        .sort!
    end
  end
end

app/views/admin/sites/_form.html.haml
= form_for [:admin, @admin_site] do |f|
  - if @admin_site.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_site.errors.count, "error")} prohibited this admin_site from being saved:"
      %ul
        - @admin_site.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :subdomain
    = f.text_field :subdomain
  .field
    = f.label :domain
    = f.text_field :domain

  .actions
    = f.submit 'Save'

app/views/admin/sites/edit.html.haml
%h1 Editing Site

= render 'form'

= link_to 'Back', admin_sites_path

app/views/admin/sites/index.html.haml
%h1 Listing Sites

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @admin_sites.each do |admin_site|
      %tr
        %td= admin_site.domain
        %td= admin_site.subdomain
        %td= link_to 'Edit', edit_admin_site_path(admin_site)
        %td= button_to 'Destroy', admin_site_path(admin_site), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }

%br

= link_to 'New Site', new_admin_site_path

app/views/admin/sites/new.html.haml
%h1 New Site

= render 'form'

= link_to 'Back', admin_sites_path